### PR TITLE
fix ConfigParser for python 3.5.2

### PR DESCRIPTION
**Pull request by sbailey**
This PR fixes the setup.py ConfigParser to work with python 3.5.2, and enables python 3.5 in the Travis tests.  I see that 3.3 and 3.4 were already included in the Travis tests; I'm not sure why this didn't come up before.  Without this fix, I get the following error when running "python setup.py test" using anaconda python 3.5.2:
```
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
```
The location of ConfigParser has apparently moved; this fix supports both 2.7 and 3.5, and presumably those versions in between (Travis will be testing those ... but why did this previously break on 3.x?)

### CODE REVIEW

**Comment by dkirkby** [comment]
This PR is superseded by #19.
